### ISSUE TITLE
Add more line-coding identities

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#100]
Today's model only ships a limited amount of line-coding-bitrate
- line-coding-NRZ-2p5G,
- line-coding-NRZ-OTU1
- line-coding-NRZ-10G
- line-coding-NRZ-OTU2

Would it be possible to add some more to cover other rates (at least 100G, 200G, 400G)?
eg:
- line-coding-100G
- line-coding-200G
- line-coding-400G

**Comment by sergiobelotti** [comment]
While layer0-types ext defines all the possible WDM interface (e.g. 2.5, 10 G, 100G ect) , in the optical impairments topology draft we consider only coherent interfaces (i.e. 100G and above)

**Comment by sergiobelotti** [comment]
As outcome from the previous meeting we need to modify layer0-types-ext  to introduce a new attribute just for bit rate >= 100G i.e. 100G,200G,300G,400G
