### ISSUE TITLE
Replace OMS/OTS link with OMS/OTS Media Channel Group (see: ITU-T Recommendations G.872 and G.807)

### ISSUE THREAD

**Issue by dieterbeller** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#101]
ITU-T G.872 (12/2019)
> 8.4.1 OMS and OTS media channel group
> The OTS media channel group (MCG) and OMS MCG are described in clause 11 of [ITU-T G.807]
> as topological constructs that are used for management control purposes. The management and
> monitoring of these entities is also described in clause 11 of [ITU-T G.807].
> NOTE – The terms OMS media link and OTS media link used in the previous version of this
> Recommendation have been replaced with the terms OMS media channel group (MCG) and OTS MCG in
> [ ITU-T G.807].

The draft text needs to be aligned with the latest revisions of the referenced ITU-T Recommendations G.807 and G.872.

**Comment by italobusi** [comment]
I have a mixed feeling about this ...

On one side, I can understand that using the terms OTS/OMS MCG would align the terminology used in the draft with the ITU-T G.807 terminology

On the other side, the OTS/OMS MCG from a topological perspective are modelled as links (at least the OMS MCG) so I am not sure whether the term MCG to represent a link would cause some confusion

**Comment by dieterbeller** [comment]
Here is the text update I prepared with the objective to align with ITU-T G.807 and describe how the new terms map to the IETF TE-topology terminology:

2.3.  OMS Media Channel Group

   According to [G.807] and [G.872], an OMS Media Channel Group (MCG)
   represents a topological construct between two WDM-TE-nodes.  In TE-
   topolgy terms, an OMS MCG corresponds to a WDM TE-link
   interconnecting two WDM-TE-nodes.  Specifically, it originates at the
   ROADM in the source WDM-TE-node and terminates at the ROADM in the
   destination ROADM including the Booster Amplifier (BA) and the Pre-
   Amplifier in the WDM-TE-nodes as well as In-Line Amplifiers (ILAs).

   OTS Media Channel Group represents a link:

     (i)  between a WDM-TE-node's BA and the adjacent ILA,
    (ii)  between a pair of ILAs,
   (iii)  between an ILA and the adjacent WDM-TE-node's PA.

   An OMS MCG can be decomposed into a sequence of OTS MCGs of type (i),
   (ii), and (iii) as listed above.  An OMS MCG (TE-link) provides the
   optical impairment data for its elements defined in the layer-0
   topology YANG model and can be retrieved by a network controller.

   For the sake of optical impairment modeling, an OMS MCG can also be
   decomposed into a sequence of elements such as BA, fiber section,
   ILA, concentrated loss, and PA.

   An OMS MCG is terminated on both ends by a link termination point
   (LTP) as defined in [RFC8345].  Links in optical transport networks
   are typically bidirectional but have to be modeled as a pair of two
   unidirectional links following the [RFC8345] modeling approach.
   Unlike TE-links, which are unidirectional, the LTPs on either end of
   the TE-link pair forming the bidirectional link, are bidirectional as
   described in [I-D.ietf-teas-te-topo-and-tunnel-modeling] and the pair
   of unidirectional links are connected to the same bidirectional LTP
   on either end of the link pair.

**Comment by ggrammel** [comment]
few nits: 
The OMS-MCG starts from the ROADM element in the WDM-TE-node, but the description of OTS-MCG doesn't cover the link between ROADM element and Booster/PA. To cover this, a case iv should be added. (see G.807 Fig 11-1)   
``` (iv) between WDM-TE-nodes ROADM and the BA/PA```

last paragraph: [RFC8345] does not specifically define LTPs. It defines Termination Points (TPs) in a generic manner. So "LTP" would better be replaced by "TP"

**Comment by sergiobelotti** [comment]
> few nits: The OMS-MCG starts from the ROADM element in the WDM-TE-node, but the description of OTS-MCG doesn't cover the link between ROADM element and Booster/PA. To cover this, a case iv should be added. (see G.807 Fig 11-1) ` (iv) between WDM-TE-nodes ROADM and the BA/PA`
> 
> last paragraph: [RFC8345] does not specifically define LTPs. It defines Termination Points (TPs) in a generic manner. So "LTP" would better be replaced by "TP"

@ggrammel @dieterbeller : thanks Gert to pointed out, we need to substitute RFC8345 with RFC8795, since LTP it is a a te-topology defined entity.

**Comment by dieterbeller** [comment]
Fixed by PR #105
