### ISSUE TITLE
copropagating raman

### ISSUE THREAD

**Issue by ggrammel** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#102]
In TIP, carrier use cases exist for copropagating Raman. It has been verified that gnpy can model those by indicating the direction (see snippet below). So the provisional limit to consider only counterpropagating raman in #91 can be lifted.

example:
        "raman_pumps": [
          {
            "power": 224.403e-3,
            "frequency": 205e12,
            "propagation_direction": "coprop"
          },
          {
            "power": 231.135e-3,
            "frequency": 201e12,
            "propagation_direction": "coprop"
          }

**Comment by sergiobelotti** [comment]
There is agreement to introduce also co-propagating option. The model as it is can support the feature using type-variety.
Only one point has to be verified: if in the case of co-propagation we can report the gain. he pump power is in the type-variety. 
The text in the draft has to updated without the limitation of counter-propagating.

**Comment by sergiobelotti** [comment]
Meeting 02/15/22:
The agreement was to add "pump-power", "frequency" and "direction" attributes as described in Gert's comment abovehttps://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/102#issue-1126058417

Meeting 02/22/22:
Esther sent a proposed description of attributes to TIP experts for revision .

**Comment by sergiobelotti** [comment]
From Esther:
Compared to GNPy data model, the pumps are listed in an ‘amplifier element’, not in a fiber. I have assumed that a given amplifier element can not hold the two co and contra propagation roles.

Final result:  
“Raman-direction”: "counter-propagating"
"Raman-pumps": [
          {
            "power": 224.403e-3,
            "frequency": 205e12,
          },
          {
            "power": 231.135e-3,
            "frequency": 201e12,
          }
        ]

Descriptions:
Raman-pumps container: list of pumps for the Raman amplifier
Power: Total pump power in W considering a depolarized pump at frequency “frequency”
Frequency: Pump central frequency in THz
Raman-direction: direction of injection of the pump in the OMS. Contra-propagating means that optical pumps are injected in opposite direction to the optical signal that
   is amplified (backward pump). Co-propagating means that the optical pumps are injected in the same direction to the optical signal that is amplified (forward pump).

   enumerate type “co-propagating” or “contra-propagating”

This porposal has been sent also to TIP experts for comments .
