### ISSUE TITLE
Issues with external OTs managed as independent TE nodes

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#106]
Investigate what are the issues when external OTs are managed as independent TE nodes (instead of being abstracted within the same TE node together with the ROADM they are connected to)

To further assess whether these issues have an impact on the optical impairments topology and7or on the base WSON/flexi-grid topology or tunnel models

**Comment by sergiobelotti** [comment]
> The slides discussed today with some additional examples to show how the bundle and component links/LTPs can be used to define per-transponder/TTP or per-transceivers optical impairments:
> 
> [external-ot-modelling-00.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8254949/external-ot-modelling-00.pptx)
> 
> The issue related to the label-hop between the external OT and the first ROADM is not relevant for the optical impairment topology model but to the tunnel model instead

new version uploaded
[external-ot-modelling-01.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8372732/external-ot-modelling-01.pptx)

**Comment by sergiobelotti** [comment]
Outcomes from the meeting on March 29th : 
The conclusions of the discussion were:
* the model already owns the tool to manage these scenarios but the way to use it is not trivial.
* Need to add to the draft a description of the use cases reported in the slides and to describe how the model address them.
* Probably an Appendix of the draft should be added for this purpose.
* **We can consider close this issue** 
* **Open an editorial issue ( #108)   to describe procedure to address the scenarios described in the slides uploaded .**
* One of the issue to consider is the spectrum allocation on link bundle
* need to open another issue in the context of the L0 tunnel (both WSON and flexgrid) on how to model the mapping between OTSi and the related component link in case of bundle (how to report which component link is used by which OTSi)

**Comment by sergiobelotti** [comment]
AP: need to review the attached slides to understand if everything has been already addressed in the model
