### ISSUE TITLE
Optical protection switching requires additional parameters

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#107]
In case optical protection switching is used , the transceiver output is splitted onto 2 paths. From our model point of view, a single OTSi is referenced at the transceiver, which means that the two paths share the same OTSi.
First this cause an issue both in the case of regeneration on one of the path. Secondly, the case where transceivers are outside of the network (then we don't know where the loop terminates) also causes an issue because it forms a loop.
I attach slides to explain the issue.
[Issue for optical protection switching representation.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8398878/Issue.for.optical.protection.switching.representation.pptx)
.

**Comment by ggalimba56** [comment]
Hi Esther,

I agree with your proposal, let me add also that we need to address the case of DWDM dynamic restoration when starting from a
Non regenerated Nominal path the controller decides to implement a regenerated restore optical path (with 2 OTSi).

Let’s discuss this point in the call.

Best Regards,

Gabriele

From: Esther Le Rouzic ***@***.***>
Reply to: ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang ***@***.***>
Date: Friday, 1 April 2022 at 17:13
To: ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang] Optical protection switching requires additional parameters (Issue #107)


In case optical protection switching is used , the transceiver output is splitted onto 2 paths. From our model point of view, an single OTSi is referenced at the transceiver. which means that the two path share the same OTSi and it forms a ring.
This cause an issue both in the case of regeneration on one of the path, and for the case transceivers are outside of the network (then we don't know where the ring terminates.
I attach slides to explain the issue.
Issue for optical protection switching representation.pptx<https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8398878/Issue.for.optical.protection.switching.representation.pptx>
.

**Comment by sergiobelotti** [comment]
In agenda for tomorrow's meeting

**Comment by ggrammel** [comment]
added one slide aboutthe shadow transponder representation. Note that the different colors used for OTSi #1b and #3b are intended to illustrate different OTSi entities, they are *not* meant to represent different wavelength.

[Issue.for.optical.protection.switching.representation(2).pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8420961/Issue.for.optical.protection.switching.representation.2.pptx)

**Comment by sergiobelotti** [comment]
added 1 slide for discussion
[Issue.for.optical.protection.switching.representation-v3.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8474831/Issue.for.optical.protection.switching.representation-v3.pptx)

**Comment by sergiobelotti** [comment]
A restricted group met each other and created a new proposal (Option 3) and added OPS capability .
We have also restructured a bit the package. 
[Issue.for.optical.protection.switching.representation-v13.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8660630/Issue.for.optical.protection.switching.representation-v13.pptx)

**Comment by sergiobelotti** [comment]
Restructured and updated version of protection package
[Issue.for.optical.protection.switching.representation-v16.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8707449/Issue.for.optical.protection.switching.representation-v16.pptx)

**Comment by dieterbeller** [comment]
The following new placeholder sections have been added to the draft as agreed on 05-Jul-22:

2.10. Protection Architectures

2.10.1.  End-to-end OTSi protection

2.10.2.  OMS MCG protection

see: [393bf62](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/commit/393bf6236e779a08e817e68a03b10d8eb820d3de)

**Comment by sergiobelotti** [comment]
[Issue.for.optical.protection.switching.representation-v20-working.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/9645591/Issue.for.optical.protection.switching.representation-v20-working.pptx)

Uploaded new version (in progress) of the slides deck. Adding proposal for capability reporting and how that would appear in the tree (also YANG code).

**Comment by ggalimba56** [comment]
Ciao Sergio,

Ecco la presentazione con le slides 23 e 24 corrette.

Buona serata,

Gabriele

From: sergio belotti ***@***.***>
Reply to: ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang ***@***.***>
Date: Monday, 26 September 2022 at 13:06
To: ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang ***@***.***>
Cc: Gabriele Galimberti ***@***.***>, Comment ***@***.***>
Subject: Re: [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang] Optical protection switching requires additional parameters (Issue #107)


Issue.for.optical.protection.switching.representation-v20-working.pptx<https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/9645591/Issue.for.optical.protection.switching.representation-v20-working.pptx>

Uploaded new version (in progress) of the slides deck. Adding proposal for capability reporting and how that would appear in the tree (also YANG code).

**Comment by sergiobelotti** [comment]
In the attached version 21 , together with Italo we added a couple of slides in the package (slide 27,28) as base for json example of the proposed solution for OPS reporting capability.  Attached there is also the json example.
The new package contains also the new slides provided by Gabriele (slides 29,30) please have a look. 
[optical.protection.switching-21.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/9696686/optical.protection.switching-21.pptx)
[ops-protection-examples-1.txt](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/9696713/ops-protection-examples-1.txt)

**Comment by sergiobelotti** [comment]
Weekly call on 10/11/2022
Attached the updated slides deck with new slides 33-34-35. The json file has been splitted in 2 : one covering example in slide 34 (ops-protection-example-2TE-nodes-full-flex)  and the other(ops-protection-example-2TE-nodes-constraints)
[optical.protection.switching-23.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/9767211/optical.protection.switching-23.pptx)
[ops-protection-examples-2-TE-nodes-full-flex.txt](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/9767245/ops-protection-examples-2-TE-nodes-full-flex.txt)
[ops-protection-example-2TE-nodes-constraints.txt](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/9767246/ops-protection-example-2TE-nodes-constraints.txt)
 for example in slide 35.
