### ISSUE TITLE
Add an Appendix to the draft describing how the YANG model supports remote optical transponders connected to a WDM-node

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#108]
In the slides uploaded in the issue #106 , and reported here for convenience, there are scenarios that the model can address but we need to add to the draft a description of the use cases reported in the slides and to describe, in a specific session (Appendix), how the model address them.  

[external-ot-modelling-01.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/8409570/external-ot-modelling-01.pptx)

**Comment by italobusi** [comment]
**2023-01-10 Italo/Sergio: few items for further discussion**

External shelf: what is the relationship between the 3 transceivers (TSPs) and the tranponder (TXP)? Three TXPs with one TSP each or one TXP with 3 TSPs? Note that the termination-type-capabilities and the supported-3r-mode attributes are defined per TXP.

Note that the relationship between the 3 TSPs and the TTPs depends on the tunnel capabilities. If the 3 tranceivers are able to support 3 OTSis belonging to the same OTSiG, the 3 TSPs must belong to the same TTP. However, the LLCL connectivity constraints (is-allowed) shall be defined between each TSP and each component LTP, to report which TSP is connected to which ROAM add/drop port.

Note that add/drop optical impairments may be reported on a coarser grained (e.g., per TTP/LTP pair or even per TTP) if they are the same

It is assumed that each component link is a single fiber carrying only one OTSi with not filters (no n,m configuration). If this assumption is correct, it is not clear how to use the flexi-n index of the media-channels list (which is the key of the list)

Slide 4: management of the label hop on the bundle link is not a topology issue by a tunnel model issue (generic or WDM technology-specific)?

**Comment by sergiobelotti** [comment]
2023-01-10 Italo/Sergio: few items for further discussion

External shelf: what is the relationship between the 3 transceivers (TSPs) and the tranponder (TXP)? Three TXPs with one TSP each or one TXP with 3 TSPs? Note that the termination-type-capabilities and the supported-3r-mode attributes are defined per TXP.

Note that the relationship between the 3 TSPs and the TTPs depends on the tunnel capabilities. If the 3 tranceivers are able to support 3 OTSis belonging to the same OTSiG, the 3 TSPs must belong to the same TTP. However, the LLCL connectivity constraints (is-allowed) shall be defined between each TSP and each component LTP, to report which TSP is connected to which ROAM add/drop port.

Note that add/drop optical impairments may be reported on a coarser grained (e.g., per TTP/LTP pair or even per TTP) if they are the same

It is assumed that each component link is a single fiber carrying only one OTSi with not filters (no n,m configuration). If this assumption is correct, it is not clear how to use the flexi-n index of the media-channels list (which is the key of the list)

Slide 4: management of the label hop on the bundle link is not a topology issue by a tunnel model issue (generic or WDM technology-specific)?
[tranceivers-llc-00.-.ib (8).pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/10434160/tranceivers-llc-00.-.ib.8.pptx)
[external-ot-modelling-02.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/10434166/external-ot-modelling-02.pptx)

**Comment by sergiobelotti** [comment]
[external-ot-modelling-03.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/10434247/external-ot-modelling-03.pptx)

**Comment by sergiobelotti** [comment]
first draft of Appendix B is included in commit 026df68
