### ISSUE TITLE
Tilt target description does not state if it is versus frequency

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#109]
In order to avoid ambiguity, we should state clearly if the tilt target is defined versus frequency or versus wavelength.

**Comment by sergiobelotti** [comment]
#38 
see comment and proposed definition to be added to "tilt" 
https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/38#issuecomment-1040294768
