### ISSUE TITLE
Muxponders' configuration constraints

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#120]
See https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/issues/56

**Comment by sergiobelotti** [comment]
This issue will be discussed in the context of flexible g rid meeting.  We will take it open till there are no feedback form the discussion in the flexible grid context.

**Comment by sergiobelotti** [comment]
Call on September 12:
There is already a proposal in the context of flexible grid. We need to discuss in the flexible grid call on Thursday if it would be better to add the modification here in Optical Impairment to make the updated feasible for both WSON and Flexgrid NW.

**Comment by sergiobelotti** [comment]
Call on September 09-26-23:

Aihua presented some slides describing a proposal to solve the issue. https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/11530989/Muxponder.Constraints.v3.pptx

No comments during the presentation apart request for clarifications but the proposal seems a good way to solve the issue. No concerns were reaised.
The agreement is to review the slides for next week and raise question if something appears not clear.
