### ISSUE TITLE
Need clear definition of MC-e2e

### ISSUE THREAD

**Issue by ggrammel** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#122]
MC-e2e is not a term used in G.807 and requires a clear definition.

**Comment by sergiobelotti** [comment]
see minutes of January 31st [https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/commit/1e3b3dfcc24eba45eb346713e13511228d602d09](url)

**Comment by dieterbeller** [comment]
Original text:

   The MC is an end-to-end topological network construct and can be
   considered as an "optical pipe" with a well-defined frequency slot
   between one or more optical transmitters each generating an OTSi and
   the corresponding optical receivers terminating the OTSi's.  If the
   MC carries more than one OTSi, it is assumed that these OTSi's belong
   to the same OTSiG.

Proposed Update:

In this document the term MC is used to represent the "optical pipe"
with a well-defined frequency slot between the OMS MCG port of the
ROADMs containing the transceiver pair terminating the OTSi in case
the OTSiG has a single OTSi or containing multiple transceivers on either
side in case the OTSiG has multiple OTSi's carried inside the same MC.
In case of remote optical transponders, the MC represents the "optical
pipe" between the media ports of the transceivers terminating the OTSi.

**Comment by sergiobelotti** [comment]
02-07-23 weekly call:
This is the text proposed as starting point. We need all to review again and make some homework to refine that.
The discussion on the possible updates will be on the mailing list, in order to have a definite text for next call.

In this document the term E2E MC is used to represent the MC
with an assigned frequency slot between the OMS MCG port of the
ROADMs containing the transceiver pair terminating the OTSi in case
the OTSiG has a single OTSi or containing multiple transceivers on either
side in case the OTSiG has multiple OTSi's carried inside the same MC.
In case of remote optical transponders, the E2E MC represents the MC
between the media ports of the transceivers terminating the OTSi.

**Comment by sergiobelotti** [comment]
A first slight modification:

In this document the term E2E MC is used to represent the MC
with an assigned frequency slot (resulting from the configuration of all WSSes along the path) between the OMS MCG port of the ROADMs containing the transceiver pair terminating the OTSi in case
the OTSiG has a single OTSi or containing multiple transceivers on either
side in case the OTSiG has multiple OTSi's carried inside the same MC.
In case of remote optical transponders, the E2E MC represents the MC
between the media ports of the transceivers terminating the OTSi.

**Comment by sergiobelotti** [comment]
Dieter, Enrico, Italo, Gabriele and myself have created a proposed text for E2E MC definition:

"The E2E MC is defined in this document as a type of MC which is formed by the serial concatenation of all the MCs from source Transceiver media ports to destination transceiver media ports. 
An E2E MC has to be configured across all the ROADM nodes along the E2E optical path with the same nominal central frequency n and frequency slot of width m, which represents the effective frequency slot of the E2E MC. 
An E2E MC can carry a single OTSi, or multiple OTSi signals belonging to the same OTSiG."

**Comment by sergiobelotti** [comment]
> Dieter, Enrico, Italo, Gabriele and myself have created a proposed text for E2E MC definition:
> 
> "The E2E MC is defined in this document as a type of MC which is formed by the serial concatenation of all the MCs from source Transceiver media ports to destination transceiver media ports. An E2E MC has to be configured across all the ROADM nodes along the E2E optical path with the same nominal central frequency n and frequency slot of width m, which represents the effective frequency slot of the E2E MC. An E2E MC can carry a single OTSi, or multiple OTSi signals belonging to the same OTSiG."

From Gert:
 This looks very good, a few thoughts:

•	We defined a transceiver as termination of a single OTSi and Transponder as termination of an OTSiG. Is this language in line with ITU-T? if so, we probably need to state
o	The E2E MC is defined in this document as a type of MC which is formed by the serial concatenation of all the MCs from source Transponder media port to destination Transponder media port.

•	How would ITU take the statement “has to be configured…”? I believe what we want to say is that it is desirable for ROADMs to be aware of the E2E MC for ease of monitoring and configuration purposes. If that is the case, the proposal would be:
o	An E2E MC is defined across all the ROADM nodes along the E2E optical path with the same nominal central frequency n and frequency slot of width m, which represents the effective frequency slot of the E2E MC.

•	We try to avoid the term NMC, but given it exists in the context of G.807 it can be equally used to write (I only swapped OTSi for NMC) and the sentence is still correct. So I wonder if we need to add a statement to distinguish an NMCG (with terminal filters) from the E2E MC (without terminal filters)
o	An E2E MC can carry a single NMC, or multiple NMC signals belonging to the same NMCG but does not include any filtering between the media port and transceivers.

**Comment by sergiobelotti** [comment]
Weekly call February 14th :

Need to add some text to clarify the difference between the E2E MC defined in our draft and the NMCG already defined in ITU-T G.807. 
Use as proposed by Gert "defined" and not "has to be configured"

**Comment by dieterbeller** [comment]
Text update based on the agreement above regarding end-to-end MC and its difference w.r.t. the NMC as defined in ITU-T Rec. G.807 Amd 1:
```
   [G.807] defines a "media channel" as "A media association that
   represents both the topology (i.e., the path through the media) and
   the resource (i.e., frequency slot or effective frequency slot) that
   it occupies."  In this document, the term "channel" is occasionally
   used to indicate the resource of an MC (i.e., frequency slot or
   effective frequency slot), without representing topology.

   In this document, an end-to-end MC is defined as a type of MC, which
   is formed by the serial concatenation of all the MCs from source
   Transceiver media ports to destination transceiver media ports.  This
   end-to-end MC is defined across all the ROADM nodes along the end-to-
   end optical path with the same nominal central frequency n and
   frequency slot of width m, which represents the effective frequency
   slot of the end-to-end MC.  An end-to-end MC can carry a single OTSi,
   or multiple OTSi signals belonging to the same OTSiG.

   [G.807_Amd1] defines a "network media channel (NMC)" as "a type of
   media channel that is formed by the serial concatenation of all media
   channels between the media port of a modulator and the media port of
   a demodulator".  The modulator and demodulator are integral functions
   of a transceiver and their media ports do not necessarily coincide
   with the media port of the transceiver, which is associated with the
   transceiver's physical optical port.  Due to this difference, the
   end-to-end MC is defined above and is used in this document.
```
