### ISSUE TITLE
Remove key from media channel list

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#124]
In case of OT remote external shelf is assumed that each component link is a single fiber carrying only one OTSi with filters present in the ROADM (WSS) , not in TSP, so no n,m configuration in TSP. If this assumption is correct, it is not clear how to use the flexi-n index of the media-channels list (which is the key of the list)
The agreement is to delete the
key statements from the media-channel-group/media-channel lists, making the flexi-n attribute optional.

A possible issue without key is to have more elements with the same flexi-n and we cannot have 2 media-channel with the same
 flexi-n.

- [ ] @italobusi @aguoietf  to have a look to possible YANG statement (e.g.unique statement) to overcome the issue.

**Comment by italobusi** [comment]
Note that PR #129 removes the flexi-n key statement but there is a need to fix this issue:

> A possible issue without key is to have more elements with the same flexi-n and we cannot have 2 media-channel with the same
> flexi-n.
