### ISSUE TITLE
Change the name of nmc-path-id list 

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#125]
We need to change the name of nmc-path-id , with e2e-mc-path-id and related description.

**Comment by dieterbeller** [comment]
I-D text already updated - see https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/121/files/bc8f9ca50faed60cb69b9bb6c98fb5d688e33458#r1118076364
