### ISSUE TITLE
Need to update the reference to RFC8776-bis

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#139]
The references to RFC8776 should be updated with a reference to RFC8776-bis (i.e., [I-D.ietf-teas-rfc8776-update]) at least when there is a dependency on the updates to RFC8776 provided in RFC8776-bis

See: https://mailarchive.ietf.org/arch/msg/teas/1XFx6vOG-A0iCkuv5DzVVft63o0/

**Comment by dieterbeller** [comment]
Reference to RFC8776 replaced with reference to RFC8776-bis, i.e., [ietf-teas-rfc8776-update](https://datatracker.ietf.org/doc/draft-ietf-teas-rfc8776-update/)

See commit [ad98f39](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/138/commits/ad98f39ee0a9243f5b9c3cda7bb6f7088fbc55f5)
