### ISSUE TITLE
Usage of "protection-type" for OMS MCG Protection Modeled as Single Protected TE-link

### ISSUE THREAD

**Issue by manzoro** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#150]
In section 
2.10.2.2.  OMS MCG Protection Modeled as Single Protected TE-link
Of draft -13 at page 46 the following indication is present on how to model this type of protection:

```
*  "underlay": this container must not be present
*  "protection-type" (identityref) set to 'link-protection-1-plus-1'
     as defined in [I-D.ietf-teas-rfc8776-update]
```

I may have missed something, but I have the impression that from the model tree the leaf "protection-type" is part of the "underlay" group, so the two bullet above seems in conflict.

**Comment by sergiobelotti** [comment]
> In section 2.10.2.2. OMS MCG Protection Modeled as Single Protected TE-link Of draft -13 at page 46 the following indication is present on how to model this type of protection:
> 
> ```
> *  "underlay": this container must not be present
> *  "protection-type" (identityref) set to 'link-protection-1-plus-1'
>      as defined in [I-D.ietf-teas-rfc8776-update]
> ```
> 
> I may have missed something, but I have the impression that from the model tree the leaf "protection-type" is part of the "underlay" group, so the two bullet above seems in conflict.

@manzoro : Thanks Roberto, to have got this editorial mistake in the text. The data node to be considered is not "protection-type" , that is the protection attribute related to underlay links (primary and backup) but link-protection-type, as reported in the slide deck "optical.protection.switching-25" from which this text is inherited.
The correct YANG extract is : 
augment /nw:networks/nw:network/nt:link:
       +--rw te!
          ................................................
          +--rw te-link-attributes
          | ..............................................
          |  +--rw underlay {te-topology-hierarchy}?
          |  |  +--rw enabled?                     boolean
          |  |  +--rw primary-path
          |  |  |  .......................................
          |  |  +--rw backup-path* [index]
          |  |  |  +--rw index           uint32
          |  |  |  .......................................
          | ..............................................
          |  +--rw link-protection-type?             identityref
          | ..............................................
          ................................................

We need to fix this problem in the update we foresee for version .14.
