### ISSUE TITLE
Absolute path in grouping power-param

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#155]
The absolute path in the grouping power-param are incorrect since there is no indication of which network instance to check

However, the grouping is used in difference places and the relative paths to reach the equalization-mode in the OMS-attributes are different ...

```
  grouping power-param {
    description
      "optical power or PSD after the ROADM or after the out-voa";
    choice power-param {
      description
        "select the mode: channel power or power spectral density";
      case channel-power {
        when "/nw:networks/nw:network/nt:link/tet:te
            /tet:te-link-attributes/OMS-attributes
            /equalization-mode='carrier-power'";
        leaf nominal-carrier-power{
          type l0-types:power-in-dbm-or-null;
          description
            " Reference channel power. Same grouping is used for the
            OMS power after the ROADM (input of the OMS) or after the
            out-voa of each amplifier. ";
        }
      }
      case power-spectral-density{
        when "/nw:networks/nw:network/nt:link/tet:te
            /tet:te-link-attributes/OMS-attributes
            /equalization-mode='power-spectral-density'";
        leaf nominal-power-spectral-density{
          type l0-types:decimal-16-digits-or-null;
          units W/Hz ;
          description
            " Reference power spectral density after 
              the ROADM or after the out-voa.
              Typical value : 3.9 E-14, resolution 0.1nW/MHz";
        }
      }
    }
  }

```

**Comment by italobusi** [comment]
**Italo/Sergio**

In the current YANG model, the `equalization-mode` is defined under the `OMS-attributes` and therefore the `powar-param` choices at the output of the ROADM and at the output of all out-voas within the same OMS MCG (reported as amplifiers within the `OMS-element` list) must be consistent

Is this correct?

**Comment by EstherLerouzic** [comment]
The power-param grouping used in the amplifier is not meant to have an equalization purpose: it is just a target power information for the amplifier instance (complementary to the gain target). The fact that it is reused from equalization leads to the confusion, and my suggestion would be to have two different grouping for these powers then:
one for and equalization targets, one for the target powers of amplifier. (and maybe change the naming to avoid any confusion ?)
