### ISSUE TITLE
delta-power contains a ratio in dB. one may call it gain, however gain is only positive, where delta_p could be negative. so the type should be changed

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#158]
delta-power contains a ratio in dB. one may call it gain, however gain is only positive, where delta_p could be negative. so the type should be changed

_Originally posted by @EstherLerouzic in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/152#discussion_r1368652123_

**Comment by sergiobelotti** [comment]
call on 10/27/23:
As consequence of Esther's comment we need to introduce a new type as "ratio-in-db".
