### ISSUE TITLE
have automatic tests

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#19]
it could be easier to have automatic testing when pushing:
- test that file is valid
- test that pushed tree corresponds to automatice generated tree

**Comment by EstherLerouzic** [comment]
adressed with PR #20

**Comment by italobusi** [comment]
PR #20 has been obsoleted by PR #31 

What is the relationship with PR #32?

**Comment by EstherLerouzic** [comment]
>
> PR #20 has been obsoleted by PR #31
>
Yes indeed
> 
> What is the relationship with PR #32?
>
In this new test I just make a check that the yang format is up to ietf requirements in terms of length of lines, indents, use of quotes, namings .... the report of the test shows all the formating issues detected by the pyang command. 
I propose to discuss this in a confcall, to have the feedback from the group about it. 
> I have linked this issue with both PR #31 and #32: the issue will be closed automatically when both pull requests are merged
> 
> @EstherLerouzic : is it correct?
>
I don't know, let's discover that!

**Comment by italobusi** [comment]
Let's discuss in the next confcall. I have added the "help wanted" to highlight the need for discussion at the confcall

**Comment by sergiobelotti** [comment]
Ca we consider closed this issue with PR #31 and PR #32 ?

**Comment by sergiobelotti** [comment]
Closed. Remaining test (formatting test related to IETF formatting rules) will be added with a new open issue.
