### ISSUE TITLE
Modelling of 3R Regenerators

### ISSUE THREAD

**Issue by dieterbeller** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#23]
Optical transponders can also be configured as 3R regenerators. The L0 topology YANG model currently does not support 3R regeneartors and therefore needs to be extended.

**Comment by italobusi** [comment]
As an input for discussion, please find some initial thoughts and scenarios for 3R modelling:

[3R-Modelling-00.pptx](https://github.com/younglee-ietf/ietf-optical-impairment-yang/files/3631432/3R-Modelling-00.pptx)

I still need to add some scenarios where the WDM network is a server-layer network for an OTN network switching the HO-ODUk

**Comment by italobusi** [comment]
Slides updated based on the feedbacks/discussions during the 2019-09-19 call:

[3R-Modelling-01.pptx](https://github.com/younglee-ietf/ietf-optical-impairment-yang/files/3632232/3R-Modelling-01.pptx)

**Comment by italobusi** [comment]
Some additional updates:

[3R-Modelling-02.pptx](https://github.com/younglee-ietf/ietf-optical-impairment-yang/files/3657159/3R-Modelling-02.pptx)

**Comment by dieterbeller** [comment]
2 options how 3R regenerators can be realized using optical transponders.
[3R configs.pptx](https://github.com/younglee-ietf/ietf-optical-impairment-yang/files/3657468/3R.configs.pptx)

**Comment by sergiobelotti** [comment]
In the prospective of a topology model for path computation as in our context one basic point is the accessibility and availability of a 3R or wavelenght converter. To model this IETF has already provide in WSON a "three stage model" as drawn in the attached picture. Reference is RFC 6163.

**Comment by italobusi** [comment]
[3R-Modelling-03.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5312928/3R-Modelling-03.pptx)

**Comment by ggrammel** [comment]
[3R-Modelling-04.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5334183/3R-Modelling-04.pptx)

**Comment by sergiobelotti** [comment]
> [3R-Modelling-04.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5334183/3R-Modelling-04.pptx)

@ggrammel : Thanks for contribution Gert. Have you added some slides or also modified previous Italo's slides? Just to easy the reading...

**Comment by ggrammel** [comment]
Hi Sergio,

I added on Italo’s and used color marks to highlight the discussion points.

Gert

**Comment by italobusi** [comment]
Few comments from @italobusi @ggalimba56 @egriseri @sergiobelotti after having read draft-ietf-teas-sf-aware-topo-model-07:

- Missing the list of SFs/NFs available on a given node
- How to map on the physical transponders (especially when the same transponder can be used by a TTP or by a 3R)?
- How to model the case where there are two intermediate transponders are located on different NEs with a grey interface?
- How to model unidir and bidir 3R configurations (see next slides)?

[3r-sf-comments-00.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6375906/3r-sf-comments-00.pptx)

**Comment by sergiobelotti** [comment]
Just as reminder these the 2 options discussed during the May 4 call:

1.  Use the service function topology model, introducing a new de-facto topology entity, “service-function 3R” and move the list of transponders under the node and provide a list of pointers between the TTP and the 3R to the list of transponders.
2. Use the usual transponders list under TTP, and use pointers to two TTPs as 3R functionality. In this case , Italo said, the TTPs would not only provide the list of transponders used by the 3R but TTP local link connectivity would also provide the impairments of the ROADM add/drop paths towards the 3R.

As feedback of a discussion among Julien, Esther, Italo, Dieter, Enrico and myself
this a first proposal for option 2 :

 augment /nw:networks/nw:network/nw:node/tet:te
            /tet:tunnel-termination-point:
    +--ro otsi-group* [otsi-group-id]
    |  +--ro otsi-group-id    int16
    |  +--ro otsi* [otsi-carrier-id]
    |     +--ro otsi-carrier-id           int16
    |     +--ro transponder-ref?          leafref
    |     +--ro transceiver-ref?          leafref
    |     +--ro configured-mode?          leafref
    |     +--ro OTSi-carrier-frequency?   frequency-thz
    |     +--ro tx-channel-power?         dbm-t
    |     +--ro rx-channel-power?         dbm-t
    |     +--ro rx-total-power?           dbm-t 
    +--ro transponder* [transponder-id]
       +--ro transponder-id    uint32
       +--ro transceiver* [transceiver-id]
          +--ro transceiver-id     uint32

         // Container with all attributes 
          +--ro 3R-attributes
             +--ro supported-3R-modes?  //values could be uni-dir, bi-dir,
             +--ro terminating-entity?  //values could be termination,3R,termination-and-3R (wavelength, tunnel)

// find a way to associate the 2 transceivers for 3R. keep association between 2 transceivers
          +--ro ttp-ref           -> ../../../../tet:tunnel-termination-point/tet:tunnel-tp-id
          +--ro transponder-ref   -> ../../../../tet:tunnel-termination-point[tet:tunnel-tp-id=current()/../ttp-ref]/
                                      transponder/transponder-id
          +--ro transceiver-ref   -> ../../../../tet:tunnel-termination-point[tet:tunnel-tp-id=current()/../ttp-ref]/
                                     transponder[transponder-id=current()/../transponder-ref]/transceiver/transceiver-id                               
          +--ro supported-modes
             +--ro supported-mode* [mode-id]
                +--ro mode-id                      string
                +--ro (mode)
                   +--:(G.698.2)
                   |  +--ro standard-mode?         standard-mode
                   +--:(organizational-mode)
                   |  +--ro organizational-mode
                   |     +--ro operational-mode?
                   |     |       operational-mode
                   |     +--ro organization-identifier?
                   |     |       organization-identifier
                   |     +--ro min-central-frequency?
                   |.....................................................................................................  
                   +--:(explicit-mode) 
                      +--ro explicit-mode
                         +--ro supported-modes
                         |  +--ro supported-application-codes*
                         |  |       -> ../../../mode-id
                         |  +--ro supported-organizational-modes*
                         |          -> ../../../mode-id
                         +--ro line-coding-bitrate?
                         |       identityref
                         +--ro max-polarization-mode-dispersion?
                         |       decimal64
                         +--ro max-chromatic-dispersion?
                         |       decimal64
                         |................................................................................................................................
  
There are still some aspects to discuss:
1) Relationship between OTSiG and OT , transceivers: how many OTSiG are associated to 1 OT , 1 or many. At the moment the model leaves full flexibility but we should shrink a bit the options.
2) The 3R is created with an association between transceivers or OT? The present proposal supposes to associate two transceivers, with full flexibility, the 2 transceivers can belong to the same OT, different OT and even under different TTP.

**Comment by agva123** [comment]
For Option 1a regarding modeling 3R regenerators as service functions, below is the proposed YANG tree by Italo and me:

  augment /nw:networks/nw:network/nw:node/tet:te
          /tet:te-node-attributes:
    +--rw service-function
       +--rw service-function [service-function-id]
          +--rw service-function-id  string
          +--rw service-function-type identityref
          +--rw connection-point [sf-connection-point-id]
             +--rw sf-connection-point-id string
             +--rw sf-connection-point-type identityref

  augment /nw:networks/nw:network/nw:node/tet:te
          /tet:te-node-attributes:
    +--ro transponder* [transponder-id]
       +--ro transponder-id    uint32
       +--ro transceiver* [transceiver-id]
          +--ro transceiver-id     uint32
          +--ro supported-modes
          .............................

  augment /nw:networks/nw:network/nw:node/tet:te
          /tet:tunnel-termination-point:
    +--ro transponder* leafref

  augment /nw:networks/nw:network/nw:node/tet:te
          /tet:tunnel-termination-point:
    +--ro transponder* leafref

  augment /nw:networks/nw:network/nw:node/tet:te
          /tet:te-node-attributes:

// when the service-function-type is 3r-regen
   augment /nw:networks/nw:network/nw:node/tet:te
           /tet:te-node-attributes/tet-sf:service-function/tet-sf:service-function:
    +--rw 3r-directionality enum (unidir, bidir)
       +--rw regen-level (ODU, OTU, client-signal)   // to be further refined

// when the service-function-type is 3r-regen
   augment /nw:networks/nw:network/nw:node/tet:te
           /tet:te-node-attributes/tet-sf:service-function/tet-sf:service-function
           /tet-sf:connection-point:
    +--ro transponder* leafref

// when the service-function-type is 3r-regen
   augment /nw:networks/nw:network/nw:node/tet:te
           /tet:te-node-attributes/tet-sf:service-function/tet-sf:link-terminations
           /tet-sf:link-termination:
    +--ro add-path-impairments?    leafref
    +--ro drop-path-impairments?   leafref
