### ISSUE TITLE
OTSi terminology alignment with G.807

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#25]
Align the draft terminology with the OTSi terminology in G.807

See: https://datatracker.ietf.org/liaison/1649/

**Comment by italobusi** [comment]
**2019-08-01 CCAMP Call**

See slides: [otsi-clarification-04.pptx](https://github.com/younglee-ietf/ietf-optical-impairment-yang/files/3462305/otsi-clarification-04.pptx)

**Comment by italobusi** [comment]
@ggalimba56 : looking at the examples described during the call (https://github.com/younglee-ietf/ietf-optical-impairment-yang/issues/25#issuecomment-517780981), it is not very clear how it is possible to optimize spectrum efficiency by not requiring the NMC frequency slot to stay on the ITU-T flexible grid

**Comment by italobusi** [comment]
ITU-T has approved G.807 in February:

https://www.itu.int/rec/T-REC-G.807/en

Work has started for a new Amendment to provide some clarifications on the OTSi/NMC terms

Initial thoughts are available in this document:

https://www.itu.int/md/T17-SG15-200127-TD-GEN-0364/en

**Comment by ggrammel** [comment]
https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/commit/ff2149feadc3acb7c3b9a9bb59892fb3a3ae4848

**Comment by dieterbeller** [comment]
This open Issue should be resolved with https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/commit/026df68805da609b62850ff8d5404c224c4a9119
