### ISSUE TITLE
Layer0type has changed Flexi-n type from uint16 to int16

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#30]
detected with automatic tests
flexi-m uint16 (must be positive)
flexi-n **can be negative** , so the changes makes sens to me
tree should be corrected

**Comment by italobusi** [comment]
@EstherLerouzic : would this issue be fixed once we merge PR #31?

**Comment by EstherLerouzic** [comment]
Yes I think so
