### ISSUE TITLE
Referencing the latest versions of YANG models in test_yang.py

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#33]
This piece of code needs to be maintained to get the latest version of the drafts until the automatic retrieval is implemented (TODO)

_Originally posted by @italobusi in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/31_

**Comment by sergiobelotti** [comment]
Can we consider closed with PR #31 ?

**Comment by sergiobelotti** [comment]
Closed with PR #31 . Test_YANG is using the last L0-type-ext in the github (not the IETF catalog)
