### ISSUE TITLE
power equalization rules for the OMS

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#37]
what is the frequency slot used for measurement?

_Originally posted by @ggrammel in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/36#discussion_r490292694_

**Comment by EstherLerouzic** [comment]
I suggest to change the name of this issue to "power equalization rules for the OMS".
The power defined with "nominal power or power spectral density" only gives us 2 rules to apply power on channels when computing performance on candidate paths. 
- first the values are not well defined in the draft test, so it is hard to kow where these values are taken on the OMS (the general value of the OMS)
- second, I am not sure that these only 2 values are enough to cover all vendor cases today or in the future
- third for both values, a definition of the spectrum to take into account is needed (flexi_m ? carrier width?, ...)

**Comment by italobusi** [comment]
> I suggest to change the name of this issue to "power equalization rules for the OMS".

I agree with this suggestion

> The power defined with "nominal power or power spectral density" only gives us 2 rules to apply power on channels when computing performance on candidate paths.
> 
> * first the values are not well defined in the draft test, so it is hard to kow where these values are taken on the OMS (the general value of the OMS)

I agree

> * second, I am not sure that these only 2 values are enough to cover all vendor cases today or in the future

This might not be a major issue since the current definition is a choice which can be extended either by updating this standard module or by vendor-specific augmentations

However, we may still need to update the current choice definition if there is a need to support some vendor cases today which cannot be supported by the current YANG model.

> * third for both values, a definition of the spectrum to take into account is needed (flexi_m ? carrier width?, ...)

I agree

**Comment by sergiobelotti** [comment]
> > I suggest to change the name of this issue to "power equalization rules for the OMS".
> 
> I agree with this suggestion

SB> I agree as well , maybe a more clear text has to be agreed.
> 
> > The power defined with "nominal power or power spectral density" only gives us 2 rules to apply power on channels when computing performance on candidate paths.
> > 
> > * first the values are not well defined in the draft test, so it is hard to kow where these values are taken on the OMS (the general value of the OMS)
> 
> I agree
SB: the definition were come out of the discussion with Jean-Luc at the beginning of the draft. Who would like to take actions to modify and propose new text for the nominal-channle-power and power-spectral-density?

> 
> > * second, I am not sure that these only 2 values are enough to cover all vendor cases today or in the future
> 
> This might not be a major issue since the current definition is a choice which can be extended either by updating this standard module or by vendor-specific augmentations
> 
> However, we may still need to update the current choice definition if there is a need to support some vendor cases today which cannot be supported by the current YANG model.

SB> I agree , augmentation is always possible.
> 
> > * third for both values, a definition of the spectrum to take into account is needed (flexi_m ? carrier width?, ...)
> 
> I agree

SB> OK, I think if we are talking about spectrum related to frequency slot (hosting the signal) , flex_m is the correct parameter. OTSi-carrier-bandwidth is related to the carrier .

**Comment by EstherLerouzic** [comment]
here are the slides I presented today
[delta_power_v2.pdf](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6189827/delta_power_v2.pdf)
