### ISSUE TITLE
do we have a crisp definition at which point in frequency the tilt/gain pair applies? i.e. need to define a point and a slope. If it can't be defined in the description, another parameter would need to be added.

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#38]
do we have a crisp definition at which point in frequency the tilt/gain pair applies? i.e. need to define a point and a slope. If it can't be defined in the description, another parameter would need to be added.

_Originally posted by @ggrammel in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/36#discussion_r501015197_

**Comment by ggrammel** [comment]
ITU-T G661 defines Gain Tilt as:
Multichannel gain tilt can be expressed as follows (Gj(1), Gj(2) and Gr(1), Gr(2) being respectively the channel gains of the j-th and the reference channel at each of the two specified sets of channel input powers and j =1, 2, . . . n; n total number of channels):

GT_j = (Gj(1) - Gj(2)) / (Gr(1) - Gr(2))

There are no explicit refence channels given in the Amplifier model. Proposal is to use `upper-frequency` and `lower-frequancy` (both of which are in the model) to act as those reference channels and document it in the text.
It would also help to define whether tilt means the gain-tilt applied by the Amplifier (which would have a positive slope) or the gain tilt that needs to be compensated (negative slope).

**Comment by sergiobelotti** [comment]
tilt is defined between lower and upper frequency of the amplifier definition.
