### ISSUE TITLE
need to better specify minimum-channel-spacing parameter

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#42]
I've reported a comment @ggalimba56 : https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/36#pullrequestreview-509117992
"To better specify the minimum-channel-spacing parameter I'd like to add more info to the model like:

                      +--ro minimum-channel-spacing?
                      |  +--ro channel-spacing
                      |  |      frequency-ghz
                      |  +--ro available-baudrate
                      |  |      frequency-ghz
                      |  +--ro nyquist-spacing
                      |  |       decimal64
                      |  +--ro roll-off
                      |  |       decimal64
                      |  +--ro xtalk-penalty
                      |         int32
this is because sometimes the minimum-channel-spacing is not given but the interface specifications give the available-baudrate, the nyquist-spacing, the roll-off and the talk-penalty. With the above parameters the minimum-channel-spacing can be calculated."

**Comment by sergiobelotti** [comment]
see also : https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/pull/36#discussion_r505346052

**Comment by ggalimba56** [comment]
The Transceiver module can provide:
- channel-spacing (in GHz) indicating the total channel spacing
In alternative the module can provide:
- baud-rate (in G Baud or G Symbols per second) in general is giving the "gross" channel 
   spacing
- the nyquist-spacing (1.x factor to multiply the "gross" channel spacing for Nyquist shaped
   signal) 
- the roll-off the slope of rising and falling edge  (it is a ratio)
- the ceros-talk penalty
So if the channel-spacing can be easily calculated from the above parameters.

**Comment by sergiobelotti** [comment]
> The Transceiver module can provide:
> 
> * channel-spacing (in GHz) indicating the total channel spacing
>   In alternative the module can provide:
> * baud-rate (in G Baud or G Symbols per second) in general is giving the "gross" channel
>   spacing
> * the nyquist-spacing (1.x factor to multiply the "gross" channel spacing for Nyquist shaped
>   signal)
> * the roll-off the slope of rising and falling edge  (it is a ratio)
> * the ceros-talk penalty
>   So if the channel-spacing can be easily calculated from the above parameters.

Before to complete the definition as suggested by Gabriele, we need to change terminology about channel-spacing:
channel-spacing in IETF L0 context is defined in https://datatracker.ietf.org/doc/draft-ietf-ccamp-layer0-types/
 related to the spectral grid definition , see G.694.1 Nominal Central Frequency Granularity.
For this reason , what related to Transceiver module has to change the name and have clear definition.

**Comment by ggalimba56** [comment]
I agree with Sergio comment.  The channel-spacing definition is more related to the grid where a Carrier Central Frequency can fall.  
In the above definition we intend to describe more the bandwidth (or portion of the spectrum) required by a specific Carrier to be routed in a DWDM or SSON network. The required bandwidth as described above can be given by the transceiver vendor or can be function of the baudrate, nyquist-spacing, roll-off and cross-talk penalty.
I'd propose to use then to change the term "channel-spacing" in "net-required-bandwidth" or "net-channel-bandwidth"

**Comment by sergiobelotti** [comment]
> I agree with Sergio comment. The channel-spacing definition is more related to the grid where a Carrier Central Frequency can fall.
> In the above definition we intend to describe more the bandwidth (or portion of the spectrum) required by a specific Carrier to be routed in a DWDM or SSON network. The required bandwidth as described above can be given by the transceiver vendor or can be function of the baudrate, nyquist-spacing, roll-off and cross-talk penalty.
> I'd propose to use then to change the term "channel-spacing" in "net-required-bandwidth" or "net-channel-bandwidth"

Checking in the code definition, as required in the closed issue #29 by Dieter https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/29#issuecomment-610288875, "minimum channel spacing" wanted to represent the "transmitter-tunability-grid" (in GHz).  Instead what you have in mind it is likely already represented by  "OTSi-carrier-bandwidth"  defined as "Carrier bandwidth occupancy" . If it is correct my understanding the extension in the definition you proose for minimum channel spacing should be redirected to this attribute in case  the required bandwidth for the carrier is not directly given by the transceiver vendor .

**Comment by sergiobelotti** [comment]
As mentioned in the minute related to the call held February 16th  https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/master/minutes/minutes-2021-02-16.md , 
we need to decide YANG encoding based on the 2 alternatives :

1. OTSi-carrier-bandwidth attribute is in alternative of the 4 attributes suggested by Gabriele available-baudrate, nyquist-spacing, roll-off, xtalk-penalty, used to compute the bandwidth required by a specific Carrier. A "choice" is needed in YANG
2. All the parameters are needed and useful anyway in the model,OTSi-carrier-bandwidth + the other 4 attributes .

**Comment by sergiobelotti** [comment]
From the minute of the meeting held on February 23:
"Since some the other proposed attributes (available-baudrate,nyquist-spacing, roll-off, xtalk-penalty) from which the carrier-bandwidth can be calculated, could be needed for other purposes, it was decided that these attributes will be present in the model anyway and not in alternative (choice) to "OTSi-carrier-bandwidt" as originally proposed in the issue https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/42

To be done:

AP @Italo/Sergio: to modify YANG accodingly AP @Gabriele : to provode some text for the draft

**Comment by sergiobelotti** [comment]
#37 Follow also the discussion regarding this issue for power spectral density definition that is related also to carrier-bandwidth definition.
See slides presented March 30th 
[carrier-bandwidth and related 20210329.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6242460/carrier-bandwidth.and.related.20210329.pptx)

**Comment by sergiobelotti** [comment]
> From the minute of the meeting held on February 23:
> "Since some the other proposed attributes (available-baudrate,nyquist-spacing, roll-off, xtalk-penalty) from which the carrier-bandwidth can be calculated, could be needed for other purposes, it was decided that these attributes will be present in the model anyway and not in alternative (choice) to "OTSi-carrier-bandwidt" as originally proposed in the issue #42
> 
> To be done:
> 
> AP @Italo/Sergio: to modify YANG accodingly AP @gabriele : to provode some text for the draft

Please review related PR in layer0-types-ext https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext/pull/22

**Comment by sergiobelotti** [comment]
Re-open due to the new proposal related again to carrier-bandwidth:
-add to already present "availiable-baudrate"  parameter, these new ones:
    - roll-off,
    - minimum-channel-spacing: “the minimum nominal difference in frequency between two adjacent channels" [ITU-T G.698.2 sec. 7.1.1],
- remove from parameters:
    - OTSi-carrier-bandwidth,
    - xtalk,
    - nyquist-spacing.

**Comment by sergiobelotti** [comment]
We (Dieter, Enrico and myself)  made a post-meeting (April 13th ) proposal to help AP regarding improvement definition of "minimum-channel-spacing".
This is the text:
“This attribute specifies the minimum nominal difference in carrier frequency between two adjacent OTSi signals.
(ref. G.698.2 sec.7.1.1).
The attribute value is not related to the flexible grid as defined in ITU-T Recommendation G.694.1, i.e. it is not related to the n or m value. 
If two adjacent OTSi signals are placed next to each other by at least the minimum channel spacing specified by this attribute the cross talk between the two OTSi signals can be considered negligible”.

**Comment by ggrammel** [comment]
G.698.2 refers to G.671 in terms of channel spacing which in turn defines:
- 3.2.2.17 channel spacing: The centre-to-centre difference in frequency or wavelength between adjacent channels in a WDM device. DWDM channel spacings are based on the grid found in [ITU-T G.694.1]. CWDM channel spacings are based on the grid found in [ITU-T G.694.2].

In particular the last sentence binds the "channel" to a DWDM grid, which is clearly not what we have in mind. We better stick to what we decided in #42 to not use the term  "channel"  and call the parameter "minimum-carrier-spacing".

**Comment by sergiobelotti** [comment]
> G.698.2 refers to G.671 in terms of channel spacing which in turn defines:
> 
> * 3.2.2.17 channel spacing: The centre-to-centre difference in frequency or wavelength between adjacent channels in a WDM device. DWDM channel spacings are based on the grid found in [ITU-T G.694.1]. CWDM channel spacings are based on the grid found in [ITU-T G.694.2].
> 
> In particular the last sentence binds the "channel" to a DWDM grid, which is clearly not what we have in mind. We better stick to what we decided in #42 to not use the term "channel" and call the parameter "minimum-carrier-spacing".
@ggrammel : Good catch, I agree , carrier is much better.

**Comment by italobusi** [comment]
> “This attribute specifies the minimum nominal difference in carrier frequency between two adjacent OTSi signals.
> (ref. G.698.2 sec.7.1.1).
> The attribute value is not related to the flexible grid as defined in ITU-T Recommendation G.694.1, i.e. it is not related to the n or m value.
> If two adjacent OTSi signals are placed next to each other by at least the minimum channel spacing specified by this attribute the cross talk between the two OTSi signals can be considered negligible”.

Few comments:

1. I think we need to clarify in the definition that the assumption is that the two adjacent OTSis are homogeneous
2. I agree with the proposal to rename it as "minimum-carrier-spacing", so we do not need to say anything about the grid
3. I am not sure the reference to G.698.2 sec.7.1.1 is still valid (I can take the action to check with ITU-T Q6/15 experts)
4. I am wondering whether we should say something about the case where the two adjacent OTSis are not homogeneous

Straw-man proposal:

> This attribute specifies the minimum nominal difference between the carrier frequencies of two homogeneous OTSis such that if they are placed next to each other the cross talk between them can be considered negligible.
> 
> In case of heterogenous OTSis, the minimum nominal difference between their carrier frequencies would be a function on the minimum-carrier-spacing of the two OTSis (e.g., the average) .
>

**Comment by sergiobelotti** [comment]
> > “This attribute specifies the minimum nominal difference in carrier frequency between two adjacent OTSi signals.
> > (ref. G.698.2 sec.7.1.1).
> > The attribute value is not related to the flexible grid as defined in ITU-T Recommendation G.694.1, i.e. it is not related to the n or m value.
> > If two adjacent OTSi signals are placed next to each other by at least the minimum channel spacing specified by this attribute the cross talk between the two OTSi signals can be considered negligible”.
> 
> Few comments:
> 
> 1. I think we need to clarify in the definition that the assumption is that the two adjacent OTSis are homogeneous
> 2. I agree with the proposal to rename it as "minimum-carrier-spacing", so we do not need to say anything about the grid
> 3. I am not sure the reference to G.698.2 sec.7.1.1 is still valid (I can take the action to check with ITU-T Q6/15 experts)
> 4. I am wondering whether we should say something about the case where the two adjacent OTSis are not homogeneous
> 
> Straw-man proposal:
> 
> > This attribute specifies the minimum nominal difference between the carrier frequencies of two homogeneous OTSis such that if they are placed next to each other the cross talk between them can be considered negligible.
> > In case of heterogenous OTSis, the minimum nominal difference between their carrier frequencies would be a function on the minimum-carrier-spacing of the two OTSis (e.g., the average) .

@italobusi : what do you mean with "homogeneous" vs. heterogeneous OTSi? Do you refer to otsi-carrier-bandwidth , I mean, homogeneous means the same otsi-carrier-bandwidth?

**Comment by italobusi** [comment]
> > > “This attribute specifies the minimum nominal difference in carrier frequency between two adjacent OTSi signals.
> > > (ref. G.698.2 sec.7.1.1).
> > > The attribute value is not related to the flexible grid as defined in ITU-T Recommendation G.694.1, i.e. it is not related to the n or m value.
> > > If two adjacent OTSi signals are placed next to each other by at least the minimum channel spacing specified by this attribute the cross talk between the two OTSi signals can be considered negligible”.
> > 
> > 
> > Few comments:
> > 
> > 1. I think we need to clarify in the definition that the assumption is that the two adjacent OTSis are homogeneous
> > 2. I agree with the proposal to rename it as "minimum-carrier-spacing", so we do not need to say anything about the grid
> > 3. I am not sure the reference to G.698.2 sec.7.1.1 is still valid (I can take the action to check with ITU-T Q6/15 experts)
> > 4. I am wondering whether we should say something about the case where the two adjacent OTSis are not homogeneous
> > 
> > Straw-man proposal:
> > > This attribute specifies the minimum nominal difference between the carrier frequencies of two homogeneous OTSis such that if they are placed next to each other the cross talk between them can be considered negligible.
> > > In case of heterogenous OTSis, the minimum nominal difference between their carrier frequencies would be a function on the minimum-carrier-spacing of the two OTSis (e.g., the average) .
> 
> @italobusi : what do you mean with "homogeneous" vs. heterogeneous OTSi? Do you refer to otsi-carrier-bandwidth , I mean, homogeneous means the same otsi-carrier-bandwidth?

Good question :)

In a strict sense, I would say that the two OTSis are homogeneous if they have exactly the same optical characteristics but different central frequencies

In the context of a minimum-carrier-spacing, two OTSis are homogeneous if at least they have the same otsi-carrier-bandwidth: I do expect that the minimum distance between the central frequencies between a fat and a thin OTSi would be smaller than the minimum distance between two fat OTSis.

For example, the minimum distance between two OTSis with 100GHz otsi-carrier-bandwidth should be at least 100 GHz but the minimum distance between an OTSi with 100GHz otsi-carrier-bandwidth and an OTSi with 50GHz otsi-carrier-bandwidth should be at least 75 GHz.

However, I am not sure that the otsi-carrier-bandwidth is the only common characteristics that have an impact on the minimum distance between the central frequencies of two adjacent OTSis.

Please note that the current proposal is to remove the otsi-carrier-bandwidth information:

https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/42#issuecomment-820383951

**Comment by italobusi** [comment]
Summary of the proposed changes:

- add to already present "availiable-baudrate"  parameter, these new ones:

    - roll-off,
    - minimum-carrier-spacing

- remove from parameters:

    - OTSi-carrier-bandwidth,
    - xtalk,
    - nyquist-spacing.

- update the definition of the minimum-carrier-spacing attribute as:

"This attribute specifies the minimum nominal difference between the carrier frequencies of two homogeneous OTSis (which have the same optical characteristics but the central frequencies) such that if they are placed next to each other the cross talk between them can be considered negligible.
In case of heterogenous OTSis, the minimum nominal difference between their carrier frequencies would be a function on the minimum-carrier-spacing of the two OTSis (e.g., the average) ."

**Comment by sergiobelotti** [comment]
@italo : I have one comment and one request for clarification about the proposed definition:
1) If I understood well Gabriele proposed to use "interference" and no more cross talk between the two adjacent OTSi.
2) In the second part of the definition it is said that minimum nominal difference is "a function on the minimum-carrier-spacing of the two OTSi" . But what is the minimum-carrier-spacing of the two OTSi? Is it not the context of the definition? It seems to me the story of the chicken and the egg....

**Comment by egriseri** [comment]
Hi @sergiobelotti , @italobusi : to be precise and pedant as mch as I can, Gabriele proposed to use "interference" to identify the spectral overlap which happens in this case.  I wonder if we need to define both interference and crosstalk somewhere, as crosstalk is often used as it encompasses the interference meaning Gabriele focused on.

2. the definition doesn't seem circular to me as it is  applicable to "heterogenous" OTSi's while the former part defines if for the Homogenous OTSi's. However it may be worth rewording it. The simplest way may be:
"In case of heterogenous OTSis, the minimum nominal difference between their carrier frequencies would be a function on the minimum-carrier-spacing of the two _homogeneous_ OTSis (e.g., the average) .

**Comment by sergiobelotti** [comment]
In case of heterogenous OTSis, the minimum nominal difference between their carrier frequencies would be a function of the minimum-carrier-spacing of the two homogeneous OTSis (e.g., the average) .

The definite text should be:
This attribute specifies the minimum nominal difference between the carrier frequencies of two homogeneous OTSis (which have the same optical characteristics but the central frequencies) such that if they are placed next to each other the interference due to spectrum overlap between them can be considered negligible.
In case of heterogeneous OTSi it is up to path computation engine to determine the minimum distance between the carrier frequency of the two adjacent OTSi.

**Comment by sergiobelotti** [comment]
> Summary of the proposed changes:
> 
> * add to already present "availiable-baudrate"  parameter, these new ones:
>   
>   * roll-off,
>   * minimum-carrier-spacing
> * remove from parameters:
>   
>   * OTSi-carrier-bandwidth,
>   * xtalk,
>   * nyquist-spacing.
> * update the definition of the minimum-carrier-spacing attribute as:
> 
> "This attribute specifies the minimum nominal difference between the carrier frequencies of two homogeneous OTSis (which have the same optical characteristics but the central frequencies) such that if they are placed next to each other the cross talk between them can be considered negligible. In case of heterogenous OTSis, the minimum nominal difference between their carrier frequencies would be a function on the minimum-carrier-spacing of the two OTSis (e.g., the average) ."

We can consider close this issue with the next PR .
Summary of the proposed changes:

1. add to already present "availiable-baudrate" parameter, these new ones:

- roll-off,
- minimum-carrier-spacing

2. remove from parameters:

OTSi-carrier-bandwidth,
xtalk,
nyquist-spacing.

update the definition of the minimum-carrier-spacing attribute as:
"This attribute specifies the minimum nominal difference between the carrier frequencies of two homogeneous OTSis (which have the same optical characteristics but the central frequencies) such that if they are placed next to each other the interference due to spectrum overlap between them can be considered negligible.
In case of heterogeneous OTSi it is up to path computation engine to determine the minimum distance between the carrier frequency of the two adjacent OTSi."
