### ISSUE TITLE
Interoperability with organizational modes

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#43]
There is the need to provide clarification about who can guarantee, in case of organizational mode, the interworking as ITU-T is doing in case of application code.

See: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/master/minutes/minutes-2020-12-03.md

**Comment by italobusi** [comment]
Initial text change proposal:

[transponder-text-change-proposal - 2020-12-10.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5673034/transponder-text-change-proposal.-.2020-12-10.docx)

Work is on-going to review also the other 2.5.x sections for consistency.

**Comment by ggrammel** [comment]
[transponder-text-change-proposal.-.2020-12-10-v1.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5673284/transponder-text-change-proposal.-.2020-12-10-v1.docx)
few add-ons & comments based on the minutes taken by Sergio.

**Comment by sergiobelotti** [comment]
Some comments related to the proposed text .
[transponder-text-change-proposal.-.2020-12-10-commented-sb.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5673498/transponder-text-change-proposal.-.2020-12-10-commented-sb.docx)

**Comment by sergiobelotti** [comment]
Attached the version of the text commented during the meeting. 
[transponder-text-change-proposal.-.2020-12-15-commented-all-docx.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5696368/transponder-text-change-proposal.-.2020-12-15-commented-all-docx.docx)

**Comment by EstherLerouzic** [comment]
Hello, here are my comments on this text. I am not very comfortable with many changes related on the definition of interoperability. I have the feeling that this is putting too much emphasize on the interop pocess which in my opinion is not part of our draft. I would prefer to remove these pieces.  Besides I prefer the previous wording Application code, because the use of standard mode instead may bring confusion with standards which are not ITU ones.
[transponder-text-change-proposal.-.2020-12-15-commented-all-docx _elr.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5717314/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr.docx)

**Comment by ggrammel** [comment]
Hi Esther,

Agree that text as it stands needs to be improved.  In my view, the best way forward is to step back from what and how things are currently modeled and describe the problem in more detail. Here a collection of questions I would like to see captured by the problem definition: Which cases need to be supported within and outside of standard or organizational modes? Are vendor modes different from Organizational modes (e.g. MSA) and if so how? Is there compatibility by declaring a specific mode (defined by an organization) but extend or limit it through extra parameters? What are the constraints of using an Application Code defined by ITU? …

**Comment by sergiobelotti** [comment]
> Hello, here are my comments on this text. I am not very comfortable with many changes related on the definition of interoperability. I have the feeling that this is putting too much emphasize on the interop pocess which in my opinion is not part of our draft. I would prefer to remove these pieces. Besides I prefer the previous wording Application code, because the use of standard mode instead may bring confusion with standards which are not ITU ones.
> [transponder-text-change-proposal.-.2020-12-15-commented-all-docx _elr.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5717314/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr.docx)

About the first part of the Esther's comment, I agree on that and I think he's referring to the text below attached
"It is worth noting that optical data plane interoperability is a complex task especially in a multi vendor environment. The optical interface specifications for an organization mode can be provided by a vendor or as a result of joint engineering between two or more vendors or by any other organization (e.g., fora ):

•	Vendor specific organizational modes inherently apply to transceivers of a single vendor and are not intended to be used for multi-vendor interop (i.e., the two transceivers SHOULD/MUST be from the same vendor).
•	Organizational modes developed as a result of joint engineering between two or more vendors apply only to the set of vendors which have been involved in the joint engineering and are not intended to be used for interoperability with other vendors (i.e., the two transceivers SHOULD/MUST be one of the vendors that have performed the joint engineering). Applicability to other vendors is not guaranteed and requires further joint engineering which may confirm its applicability or lead to the definition of new organization modes.
•	Other organizational modes, although aim for multi-vendor interoperability, do not always guarantee  that. Therefore some care has to be taken when using this type of organizational modes. Additional testing or joint engineering would be required to verify that.

Moreover, it is also worth noting that the fact that a given organizational mode allows interoperability on a given DWDM network does not guarantee interoperability on a different DWDM network. Additional testing or joint engineering would be required to verify that . "

What is the intention of all this piece of text in the context of a topology model?

**Comment by italobusi** [comment]
As per AP on the latest call (2020-12-22), this is the initial text proposal for the introduction:

[introduction-text-change-proposal - 2021-01-05.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5769218/introduction-text-change-proposal.-.2021-01-05.docx)

**Comment by italobusi** [comment]
> Hello, here are my comments on this text. I am not very comfortable with many changes related on the definition of interoperability. I have the feeling that this is putting too much emphasize on the interop pocess which in my opinion is not part of our draft. I would prefer to remove these pieces. Besides I prefer the previous wording Application code, because the use of standard mode instead may bring confusion with standards which are not ITU ones.
> [transponder-text-change-proposal.-.2020-12-15-commented-all-docx _elr.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5717314/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr.docx)

Some follow-up replies to Esther's comments:

[transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr-ib-haomian.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5769226/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr-ib-haomian.docx)

The text in section 2.5.2 can be greatly simplified after the introduction text clarifies the responsibility of inter-op. The text in other section 2.5.x needs to be aligned for consistency.

**Comment by sergiobelotti** [comment]
> > Hello, here are my comments on this text. I am not very comfortable with many changes related on the definition of interoperability. I have the feeling that this is putting too much emphasize on the interop pocess which in my opinion is not part of our draft. I would prefer to remove these pieces. Besides I prefer the previous wording Application code, because the use of standard mode instead may bring confusion with standards which are not ITU ones.
> > [transponder-text-change-proposal.-.2020-12-15-commented-all-docx _elr.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5717314/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr.docx)
> 
> Some follow-up replies to Esther's comments:
> 
> [transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr-ib-haomian.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5769226/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr-ib-haomian.docx)
> 
> The text in section 2.5.2 can be greatly simplified after the introduction text clarifies the responsibility of inter-op. The text in other section 2.5.x needs to be aligned for consistency.

[transponder-text-change-proposal.-.2020-12-15-commented-all-docx-010521-sb.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5770079/transponder-text-change-proposal.-.2020-12-15-commented-all-docx-010521-sb.docx)

**Comment by sergiobelotti** [comment]
> As per AP on the latest call (2020-12-22), this is the initial text proposal for the introduction:
> 
> [introduction-text-change-proposal - 2021-01-05.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5769218/introduction-text-change-proposal.-.2021-01-05.docx)

[introduction-text-change-proposal.-.2021-01-05-SB-comment.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5770209/introduction-text-change-proposal.-.2021-01-05-SB-comment.docx)

**Comment by sergiobelotti** [comment]
> As per AP on the latest call (2020-12-22), this is the initial text proposal for the introduction:
> 
> [introduction-text-change-proposal - 2021-01-05.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5769218/introduction-text-change-proposal.-.2021-01-05.docx)

Here the agreed text after today's call January 5th , 2021
[introduction-text-change-proposal-2021-01-05.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5770794/introduction-text-change-proposal-2021-01-05.docx)

**Comment by sergiobelotti** [comment]
> > Hello, here are my comments on this text. I am not very comfortable with many changes related on the definition of interoperability. I have the feeling that this is putting too much emphasize on the interop pocess which in my opinion is not part of our draft. I would prefer to remove these pieces. Besides I prefer the previous wording Application code, because the use of standard mode instead may bring confusion with standards which are not ITU ones.
> > [transponder-text-change-proposal.-.2020-12-15-commented-all-docx _elr.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5717314/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr.docx)
> 
> Some follow-up replies to Esther's comments:
> 
> [transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr-ib-haomian.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5769226/transponder-text-change-proposal.-.2020-12-15-commented-all-docx._elr-ib-haomian.docx)
> 
> The text in section 2.5.2 can be greatly simplified after the introduction text clarifies the responsibility of inter-op. The text in other section 2.5.x needs to be aligned for consistency.

Here the text modifications to section 2.5.x after the today's call 2021-01-05 
[transponder-text-change-proposal-2021-01-05-after-the-call.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5770870/transponder-text-change-proposal-2021-01-05-after-the-call.docx)

**Comment by dieterbeller** [comment]
> Here the agreed text after today's call January 5th , 2021
> [introduction-text-change-proposal-2021-01-05.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5770794/introduction-text-change-proposal-2021-01-05.docx)

Here is the new paragraph I added to our I-D (Introduction):

    It is worth noting that optical data plane interoperability is a
    complex topic especially in a multi vendor environment and usually
    requires joint engineering, which is independent from control plane
    and management plane capabilities.  The YANG data model defined in
    this draft is providing sufficient information to enable optical
    impairment aware path computation.
    Optical data plane interoperability is outside the scope of this
    draft.

**Comment by dieterbeller** [comment]
I updated the paragraph in section 2.5.2 as follows:

    An organization may define the operational modes to include the
    optical power and carrier frequency related properties following the
    application code approach as defined in ITU-T Recommendation G.698.2
    [G.698.2].  In such a case, the explicit optical power and carrier
    frequency related optional attributes shall be omitted in order to
    avoid redundant information in the description of the transceiver
    capabilities.  If these attributes are provided in addition to the
    operational modes including these attribute values implicitly, the
    parameter values provided explicitly replace the implicit values and
    take precedence.  This shall, however, only be an done in exceptional
    cases and shall be avoided whenever possible.  In case an implicitly
    given range is extended utilizing the explicit optional attributes, a
    path computation policy rule may be applied to select a value
    preferably from the range defined implicitly and to only select a
    value from the extended range if no path can be found for values in
    the implicitly defined range.  Path computation policy is outside the
    scope of this topology YANG model.

    In summary, the optical power and carrier frequency related
    attributes shall either be described implicitly by the operational
    mode following the definition provided by that organization or shall
    be described explicitly when the optical power and carrier frequency
    related properties are not included in the operational mode
    definition.

I added these two sentences at the end of the first paragraph:

_In case an implicitly given range is extended utilizing the explicit optional attributes, a path computation policy rule may be applied to select a value preferably from the range defined implicitly and to only select a value from the extended range if no path can be found for values in the implicitly defined range.  Path computation policy is outside the scope of this topology YANG model._

I put the last sentence in a separate paragraph (see above).

**Comment by sergiobelotti** [comment]
Uploaded the text related to section 2.5, after the introduction of Dieter's text and a general clean-up and consistency check.
Please have a look at that , comment/amend what is needed so that we can upload the text in the new version the draft.
[transponder-mode-text-section-2.5-2021-15-01.docx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5821365/transponder-mode-text-section-2.5-2021-15-01.docx)

**Comment by sergiobelotti** [comment]
Closed with new text section 2.5 approved during weekly call on January 19th https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/commit/a84f4b04e5566ce7288529673486011b3a604e50.
The new section will be part of the new updated version of the draft, in the view of IETF-110 online meeting.
