### ISSUE TITLE
Missing amplifier ports id in OMS element

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#45]
Current data model lists all elements within an OMS with an index and an uid, there is no port identifier. However, in the case we need to compute the loss of a specific fiber span based on the measured ouput power from the input amplifier and input power of the output amplifier of the span, we can not request the measurement info on these ports using the current model.
I think adding ports id  is needed.
It could be for example (and to be discussed!)
....
          +--ro elt-index    uint16
          +--ro uid?         string
          **+--ro input-port-id       
          +--ro output-port-id**
          +--ro type         identityref
          +--ro element
....

**Comment by italobusi** [comment]
![image](https://user-images.githubusercontent.com/12461741/104323662-ba50c980-54e6-11eb-88f6-5f16e23b6db3.png)

**Comment by EstherLerouzic** [comment]
here is the workflow discussed with the proposed attribute to add in amplifier elements
[workflow-amp-ports_jm.pdf](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/5836203/workflow-amp-ports_jm.pdf)

**Comment by ggrammel** [comment]
Depending on the outcome of the general Amplifier Model see #46 , the port identification needs to be more specific to allow identification of ports for each band-amp. Since the settings for C or L-Band can differ, the port-ID would need to reference each band-AMP individually e.g:

```
+--ro element
         +--ro elt-index uint16
         +--ro uid? string
         +--ro type identityref
         +--ro element
         +--ro (element)?
                +--:(amplifier)
                |  +--ro amplifier* [amp-id]
                   +--ro input-port-id
                   +--ro output-port-id
```

**Comment by sergiobelotti** [comment]
As reported in the minute https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/master/minutes/minutes-2021-01-26.md we agree to consider splitter/combiner subsumed by type-variety attribute. Moreover, even if frequency range is a property of a type-variety, with the multiple band amps, we can rely on the frequency range to identify which amp is concerned, and to get the related values attributes . In my view we do not need anymore to introduce input and output port.

**Comment by sergiobelotti** [comment]
see comment above https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/45#issuecomment-769684812
