### ISSUE TITLE
Topology model extensions to support C+L band DWDM networks including all network topology components

### ISSUE THREAD

**Issue by dieterbeller** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#51]
Following the optical amplifier model extensions to support C+L band amplifiers, model extensions shall be added for all the other network components in the topology model where L-band extensions are needed (e.g. ROADM model extensions).

A similar approach shall be used as for the amplifier model extensions where a copy of the C-band tree was added as a new sub-tree for the L-band to a new list containing these sub-trees for the different bands (See #46).

**Comment by ggrammel** [comment]
I can't find a "C-band tree" or "L-band tree"  in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/46#issuecomment-767559764.

**Comment by EstherLerouzic** [comment]
C+L booster or preamp amplifiers may have multiple input/output port from/to ROADM ports which makes the mapping of the OMS to the link more difficult. In addition to that, the current model might not be able to represent the cases when there is one more amp on one band (ILA or booster/preamp). I have added a drwing to explain this

**Comment by EstherLerouzic** [comment]
[C+Lroadm.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6029628/C%2BLroadm.pptx)

**Comment by EstherLerouzic** [comment]
Here is an update of the drawing: I think that the model can handle the particular cases... only the mapping issue remains... let's discuss this !
[C+Lroadm_v2.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6050829/C%2BLroadm_v2.pptx)
