### ISSUE TITLE
Remove transponder-attributes grouping?

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#55]
The grouping transponder-attributes has been defined but it is not used in the model

Check whether it has been superseded by the definitions in layer0-types-ext or something needs to be added in layer0-types-ext and then remove it from the optical impairments topology YANG model

Co-authored-by: sergiobelotti <sergio.belotti@nokia.com>

**Comment by sergiobelotti** [comment]
I've checked in the code, common-explicit-mode in layer0-types-ext supersedes the content of this grouping.
Basically the content is related to : modulation-types, baud-rates , FEC types, FEC code-rate, FEC threshold .
All these information is contained in the common-explicit-mode.

**Comment by sergiobelotti** [comment]
@dieterbeller to check again the grouping and see if the attributes is already covered by other group

**Comment by dieterbeller** [comment]
I checked the latest committed YANG file (PR #78) and the grouping "transponder-attributes" is indeed not used anywhere in ietf-optical-impairment-topology.yang. So, it can be removed. The attributes seem to be covered now by the grouping common-explicit-mode in ietf-layer0-types-ext.yang.

**Comment by sergiobelotti** [comment]
> I checked the latest committed YANG file (PR #78) and the grouping "transponder-attributes" is indeed not used anywhere in ietf-optical-impairment-topology.yang. So, it can be removed. The attributes seem to be covered now by the grouping common-explicit-mode in ietf-layer0-types-ext.yang.

Constructive comment , so we can consider closed this issue with the next PR. Thanks Dieter .
