### ISSUE TITLE
Issue tags for developpers

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#71]
Would it be possible to issue tags to have read only states of the yang ? This would ease to point to the correct same version in development process of depending applications (tag is read only, whereas revision date change is manual process, and may not ensure several versions with the same date)

**Comment by sergiobelotti** [comment]
Call on September 12 :
when a YANG modification is done , the YANG revision date has to be changed . It would be good if automatically the revision red flag could be introduced. (warning).
But we all agree to delete the issue from this specific context.
