### ISSUE TITLE
OTSi group should be network wide

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#75]
The list of OTSI group is currently placed in the tunnel-termination-point with otsi-group-id int16.

However, the otsi-group-id has not a local meaning it should be the same all along the path including at the receiver side (and maybe also accross two networks) so that:
- OTSi group should be moved under the network, and only referenced in ttp
- int16 is not enough 
- int might not be the best way (string ? uri? uuid ? may be more general solutions). for example we might  want not to reuse an id even if the OTSIG has been removed.

besides, otsi-carrier-id is also int16, but maybe uint16 would be better

**Comment by sergiobelotti** [comment]
OTSi group could be a string , more flexible.

**Comment by sergiobelotti** [comment]
How is the relationship between OTSi group identifier and tunnel identifiers ? 
Is really need to have OTSiG information in a topology model? 
Is really need to have OTSi information in a topology model?
