### ISSUE TITLE
How to identify OTSi reverse direction ?

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#76]
Suppose that we have a link A-B
A (ttp-id 1 (otsi-group-id 1 (otsi-carrier-id 1)) ---->Link (OMS) ---->  B
A (ttp-id 2 (otsi-group-id 2 (otsi-carrier-id 10))) <----Link (OMS) <---- B

How do I know that otsi-carrier-id 1 and 10 are for the same "service" ?

**Comment by sergiobelotti** [comment]
To be aligned with OTSi ITU-T definition the best way would be to model a bidirectional OTSi as a pair of uni-directional entities, pointing to the same transceiver entity.
