### ISSUE TITLE
relative xpath in leafref

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#79]
We have defined some groupings with leafref based on relative xpath. While in the model they are used correctly (in the correct point of the tree) we need to analyze if it would not be more correct the usage of absolute xpath, with a way to force e.g. the navigation just under the our network and node (not outside our context).

RFC 8345 provide a couple of good example of the usage of absolute paths but these examples do not guarantee to stay inside the specific network .
Here a couple of examples: 
 grouping network-ref {
       description
         "Contains the information necessary to reference a network --
          for example, an underlay network.";
       leaf network-ref {
         type leafref {
           path "/nw:networks/nw:network/nw:network-id";
         require-instance false;
         }
         description
           "Used to reference a network -- for example, an underlay
            network.";
       }
     }

grouping node-ref {
       description
         "Contains the information necessary to reference a node.";
       leaf node-ref {
         type leafref {
           path "/nw:networks/nw:network[nw:network-id=current()/../"+
             "network-ref]/nw:node/nw:node-id";
           require-instance false;
         }
         description
           "Used to reference a node.
            Nodes are identified relative to the network that
            contains them.";
       }
       uses network-ref;
     }

**Comment by italobusi** [comment]
I have sent some questions to IETF YANG doctors but not yet received any reply:

https://mailarchive.ietf.org/arch/msg/yang-doctors/KQycgH7DTfA-XGHbLque09LudBk/

**Comment by sergiobelotti** [comment]
> I have sent some questions to IETF YANG doctors but not yet received any reply:
> 
> https://mailarchive.ietf.org/arch/msg/yang-doctors/8EHiqGRcAxJkv2OtSLcU9a7i848/

We have tried to modify the code and relative path following the suggestion to use "ancestor" function of XPATH, but we had  problem with yanglint validation that unfortunately is using its own XPath implementation.
See follow up of the discussion here: 
https://mailarchive.ietf.org/arch/msg/netmod/_T5BSVb-zcgyD53vt5BXshL93gY/

**Comment by sergiobelotti** [comment]
> 
following further the thread https://mailarchive.ietf.org/arch/msg/netmod/ZyG0RfpNMcVtBnnTOQ9uHDh7UQo/
,it seems there is a positive general consensus in the usage of "ancestor" function .
See below : 
Looking at the actual usage (below), the 'ancestor' approach is more
readable and easier for the writer to generate correctly.
Given that the "network" node must be present in the augment-stmt,
it is not a concern that it is used directly in the when-stmt.


 augment "/nw:networks/nw:network/nw:node/tet:te/"
        + "tet:te-node-attributes/tet:connectivity-matrices/"
        + "tet:label-restrictions/tet:label-restriction" {

    when "ancestor::nw:network/nw:network-types/"
       + "tet:te-topology/flexgt:flexi-grid-topology";

/*
    when "../../../../../../nw:network-types/tet:te-topology/"
       + "flexgt:flexi-grid-topology" {
      description
        "Augmentation parameters apply only for networks with
         flexi-grid topology type.";
    }
*/

**Comment by sergiobelotti** [comment]
Conclusion : The usage of relative path is unavoidable in some cases . An alternative solution would be to use the "ancestor" function but there is a limited  support in YANG tool chain.
