### ISSUE TITLE
3R description improvement ITU Reference

### ISSUE THREAD

**Issue by ggrammel** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#80]
https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/blob/master/I-D_in_xml/draft-ietf-ccamp-optical-impairment-topology-yang.xml details need adjustments:

line 875 and following:
   ```
A functional
   description of an optical 3R regeneratator can be found in
   <xref target="G.680"/>, section 7.6. Following this description, a 3R
   regenearator is considered as layer 0 entity because it only
   terminates the modulated optical signal and processes the FEC for correcting
   any bit errors that may be present in the digital signal after the
   (coherent) demodulation of the optical signal (FEC termination in receive
   direction and FEC re-creation in transmit direction). Apart from the error
   correction, there is no processing of the digital signal, i.e., the payload
   of the signal is not processed and passed transparently from the receiver
   including the demodulator to the transmitter including the modulator.
```

Issue:

1. G.680 apparently describes an "optical 3R regenerator" as an All Optical Network Device (AON) which doesn't include electrical processing (see below). It doesn't appear to be a good reference for back-to-back transponders.
```
7.6 Functional description of an optical 3R regenerator
An optical 3R regenerator is a device or sub-system that performs simultaneously in the optical domain the "re-shaping", "re-amplification" and "re-timing" functions on an optical signal. Thus this device or sub-system restores the amplitude of the signal to a level suitable for onward transmission, removes any amplitude noise or distortion present on the waveform and also re-times the signal to remove any timing jitter that may be present.
```
and
```
8.6 Optical 3R transfer parameters
The optical 3R regenerators may be a key device in future AONs. However, at present, they cannot be considered technologically ready to be introduced into the current telecommunication networks. Therefore, a model for their characterization is for further study.
```

A better ITU reference may be G.872 
`Figure 7-6 shows the case where regeneration is performed below the OTUCn layer, in this case ODUCn TCM is not supported.`
`Figure7-4 –ODUCn layer network example The  ODUCn  forwarding  point  (FP) represents the  location  of ODUCn regeneration  and  allows ODUCn tandem connection monitoring (TCM).`

**Comment by ggrammel** [comment]
to capture the discussion: referencing statement made in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/81#issuecomment-870401120 which relates to #80
>For our internal check with ITU-T expert, simply, an ITU-T definition reference does not exist


Note: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/80#issue-927264514 vs. https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/81#issuecomment-870401120 hints to a potential terminology issue

**Comment by ggrammel** [comment]
Another option for a reference could be Rec. ITU-T G.798.1 (01/2013). It covers a "3R regeneration compound function" and illustrates "Figure 10-4 – Example of wavelength ADM showing various connections".
<img width="588" alt="Screenshot 2021-06-29 at 12 16 04" src="https://user-images.githubusercontent.com/15140692/123780802-de0c9e00-d8d3-11eb-970b-37a1a8570007.png">

**Comment by egriseri** [comment]
As far as I understand it, G.798.1 is just proposing a model for a 3R, not adding too much detail.
It looks nobody wants to define a 3R apart from "Re-timing, Re-shaping and Re-amplification" to avoid to stick to some implementation. I still think the more general we stay, the better.

**Comment by sergiobelotti** [comment]
The issue is closed with the revised text in version -07, section  #2.6 , see comment above
