### ISSUE TITLE
How to associate transceivers in a 3R configuration

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#83]
It is not fully clear how the transceivers used in a 3R configuration can be associated, especially in case of multi-carrier (OTSiG with >1 OTSi) cases

[3R-discussion-global.070621pptx.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6770568/3R-discussion-global.070621pptx.pptx)

For example, in case of 200G bidirectional regeneration (slide 14), transceivers 5 and 6 can be used to terminate two 100G OTSis on one side and transceivers 7 and 8 to terminate two 100G OTSis on the other side

Is transceiver 5 associated with 7 or with 8?

The slides show in the last 3 ones , OTSiG with only OTSi case, OTSiG with OTSi > 1, with bidir and unidir 3R configuration

**Comment by sergiobelotti** [comment]
From Igor: Today, during our weekly call (July 6th),  we discussed  describing 3R capability in a form of two pools of transceivers (West -East) out of which a pair of transceivers could be interconnected to realize a 3R function. I think we need to consider the transceiver interconnection limitations. For example, a transceiver X from pool East could be interconnected with any transceiver from pool West except for transceiver Y. 
 Therefore, I suggest  replacing the two transceiver pools with a single connectivity matrix of transceivers describing all possible/valid pairs. Obviously,  the same node may advertise more than one such CM.

**Comment by sergiobelotti** [comment]
> From Igor: Today, during our weekly call (July 6th), we discussed describing 3R capability in a form of two pools of transceivers (West -East) out of which a pair of transceivers could be interconnected to realize a 3R function. I think we need to consider the transceiver interconnection limitations. For example, a transceiver X from pool East could be interconnected with any transceiver from pool West except for transceiver Y.
> Therefore, I suggest replacing the two transceiver pools with a single connectivity matrix of transceivers describing all possible/valid pairs. Obviously, the same node may advertise more than one such CM.

From Victor: I think it is not possible to model it with a single connectivity matrix. I think it may depend on the line rate. For instance we can have a transponder (TxP A) that is 100 Gbps line and 100 Gbps client, while another transponder (TxP B) can be 100/200 Gbps line and 2x100 Gbps client. If we connect 2 TxP A to a TxP B, they can regenerate 100G signals, but not 200Gbps carriers?

**Comment by sergiobelotti** [comment]
> > From Igor: Today, during our weekly call (July 6th), we discussed describing 3R capability in a form of two pools of transceivers (West -East) out of which a pair of transceivers could be interconnected to realize a 3R function. I think we need to consider the transceiver interconnection limitations. For example, a transceiver X from pool East could be interconnected with any transceiver from pool West except for transceiver Y.
> > Therefore, I suggest replacing the two transceiver pools with a single connectivity matrix of transceivers describing all possible/valid pairs. Obviously, the same node may advertise more than one such CM.
> 
> From Victor: I think it is not possible to model it with a single connectivity matrix. I think it may depend on the line rate. For instance we can have a transponder (TxP A) that is 100 Gbps line and 100 Gbps client, while another transponder (TxP B) can be 100/200 Gbps line and 2x100 Gbps client. If we connect 2 TxP A to a TxP B, they can regenerate 100G signals, but not 200Gbps carriers?

From Igor: I am not talking about binary CM, rather, what we call detailed CM, i.e. whose entries not just say Yes/ No, but also provide qualifying/ conditional info.

**Comment by sergiobelotti** [comment]
We had a further call with smaller group of attendees to address the issue. We reached an agreement described in https://demo.hedgedoc.org/oXyjMKIUQrCa9-HsrKYFdw
see slides 5-6 of the attached deck.
[3R-discussion-global.08-05-21-issue#83.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6960488/3R-discussion-global.08-05-21-issue.83.pptx)
