### ISSUE TITLE
deref() YANG syntax usage as XPATH function

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#84]
We had yanglint compilation problem during our submission of the version 7 of the draft.
No problem with deref() with pyang compilation , form which we have free errors code in GITHUB versions.
There is a specific discussion on yanglint on the subject 
deref() function usage in path statement · Issue #544 · CESNET/libyang (github.com)
from which it seems as though ABNF of path statement in RFC7950 do not include "deref" as a valid keyword in the context of a XPATH statement.
In fact the examples in RFC7950 presents only the usage of deref() in "must" statement.
We need to check with someone in NETMOD .

**Comment by rgwilton** [comment]
It is definitely worth asking in NETMOD, but my read of RFC 7950 is that deref() is not allowed within path statements, they are more restricted.

**Comment by sergiobelotti** [comment]
> It is definitely worth asking in NETMOD, but my read of RFC 7950 is that deref() is not allowed within path statements, they are more restricted.

@rgwilton : thanks Rob for you help , this is also our conclusion also looking at different YANG code usage of deref().

**Comment by sergiobelotti** [comment]
the issue will be closed automatically with the approval of PR#96
