### ISSUE TITLE
Add optical power info on amps in/out ports

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#85]
This was raised on issue #45, as a use case for ports info. But finally we agreed to not have ports, but we did not follow up on the need for optical power (did not find an issue on that, so I start this one).

Optical power is especially needed to recompute / check consistency of span (fiber+concentrated loss) loss value, with respect to loss/gain information on elements.

**Comment by sergiobelotti** [comment]
see the tree proposal at https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/46#issuecomment-767559764

**Comment by egriseri** [comment]
Hi @EstherLerouzic, are you proposing a mandatory or optional parameter?

**Comment by EstherLerouzic** [comment]
Hi! I am just wondering if some of the mandatory parameters of the amplifier element should be set to optional instead in order to be consistent with Raman handling.
For example, I think that there can not be any "nominal-carrier-power" setting when using a Raman amplification, and I am not sure about the tilt_target: is this really meaningful in case of Raman ?
That's more a general question to be sure that we do not require non sense values for Raman.

**Comment by EstherLerouzic** [comment]
Yes I would prefer it mandatory

**Comment by sergiobelotti** [comment]
We need:

-  to add attribute "total-output-power" in the container "operational" in the grouping "amplifier-params"
- description : "It represent total output power measured in the range specified by fmin and fmax . Optical power is especially needed to re-compute / check consistency of span (fiber+ concentrated loss) loss value, with respect to loss/gain information on elements."
