### ISSUE TITLE
Explicitly say that the impairment definitions of OMS are also valid for links between shelves

### ISSUE THREAD

**Issue by EstherLerouzic** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#86]
We would like to use the model to describe a topology where the ROADMs have one/multiple external shelves with OTs.
[external_shelves.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/files/6917425/external_shelves.pptx)
For management reason we want to represent the external shelf as a te-node (in the ietf model), to represent all names and adresses (we do not want to represent the shelf+ROADM as a single abstract ROADM). The links between the OTs hosted in this shelf can be described using te-link with optical impairment augmentation to describe possible  loss or noise (the tooling provided by the model is enough to handle this case). However the external shelf does not contain any mux, so that the link between the remote transceiver and the ROADM is not an OMS. However all the impairments we have defined in our model have this 'OMS' attribute.
This mismatch between the name of the attributes (containing OMS) and its usage for non OMS links might be confusing for implementers. 

We thus would like to say explicitely in the draft that the links between ROADMs and external shelves can also be described with our model.

Currently, this sentence is in the draft:

>    [Editor's note: The modeling of remote optical transponders located
   for example in the client device with a single channel link between
   the OT and the add/drop port of the ROADM requires further
   investigations and will be addressed in a future revision of this
   document.]

Would it be possible instead to say:
The impairments related to the link between remote optical transponders located in a different shelf from the ROADM itself,
can also be modelled using the same optical impairments as those defined for a link between ROADMs (OMS).

**Comment by sergiobelotti** [comment]
> 
Following Igor's suggestion during the discussion of today's call (December 14th) , we should probably add to the proposed text that

- in the scenario the external shelf can be considered as TE-node with termination capability only (not switching)
- the external shelf is under the control of the same controller as the ROADM

**Comment by sergiobelotti** [comment]
- the external shelf is under the control of the same controller as the ROADM : the text is no more used .
-AP: @italobusi to add specific issue to clarify how the link between external shelf and ROADM is discovered .
No impact on this issue that we can consider as closed .

**Comment by sergiobelotti** [comment]
This is the "agreed" text , to be added in the draft in the next version upload (by IETF-113):
"The impairments related to the link between remote optical transponders located in a different shelf from the ROADM itself,
can also be modelled using the same optical impairments as those defined for a link between ROADMs (OMS).
In the scenario the external shelf can be considered as TE-node with termination capability only (not switching)"

**Comment by ju7ien** [comment]
Let me suggest a couple of tweaks:
"The impairments related to the link between remote optical transponders, located in a different node from the ROADM itself,
can also be modeled using the same optical impairments as those defined for a link between ROADMs (OMS).
In this scenario, the transponder-carrying node can be considered as TE-node with termination capability only (i.e. no switching)."

**Comment by sergiobelotti** [comment]
@julien : Thanks Julien for the suggested modifications, why at this point do not use the terminology proposed in issue #26 ?

"The impairments related to the link between remote optical transponders, located in a different WDM-TE-node from the ROADM itself,
can also be modeled using the same optical impairments as those defined for a link between ROADMs (OMS).
In this scenario, the transponder-carrying node can be considered as WDM-TE-node with termination capability only (i.e. no switching)."

**Comment by ju7ien** [comment]
If we agree on the terms in #26, I concur: we MUST use them here.

**Comment by dieterbeller** [comment]
Fixed by PR #105
