### ISSUE TITLE
Relationship between OTSiG and tunnel identifiers

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#87]
How is the relationship between OTSi group identifier and tunnel identifiers ? 
Is really need to have OTSiG information in a topology model? 
Is really need to have OTSi information in a topology model?

_Originally posted by @sergiobelotti in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/75#issuecomment-896041636_

**Comment by sergiobelotti** [comment]
The issue has been moved to flex grid tunnel model https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang/issues/47
