### ISSUE TITLE
Need to have OTSiG in the topology model

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang#88]
How is the relationship between OTSi group identifier and tunnel identifiers ? 
Is really need to have OTSiG information in a topology model? 
Is really need to have OTSi information in a topology model?

_Originally posted by @sergiobelotti in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/75#issuecomment-896041636_

**Comment by sergiobelotti** [comment]
AP: Dieter to provide some text regarding the relationship between the related OTSiG and OTSi identifier.

**Comment by dieterbeller** [comment]
I am in favor of the current hierarchical approach where the otsi-group-id (string) uniquely identifies the OTSiG in the network and where the contained otsi-carrier-id (uint16) are identified within the scope of the otsi-group-id. This approach seems to be very reasonable to me. Here is a text proposal for sections 2.3.1 and 2.3.2:

- additional paragraph added to 2.3.1 Optical Tributary Signal (OTSi):

The OTSi signals in the YANG model are described by augmenting the network and each OTSi signal is uniquely identified by its  otsi-carrier-id, which is unique within the scope the OTSiG  [see _ref to following section_] the OTSi belongs to.

- additional paragraph added to 2.3.2 Optical Tributary Signal Group (OTSiG):

All OTSiGs are described in the YANG model by augmenting the network and each OTSiG is uniquely identified by its otsi-group-id, which is unique within the network. Each OTSiG also contains a list of the OTSi signals belonging the the OTSiG.
